[package]
name = "matter"
version = "0.1.0-alpha2"
authors = ["Nicholas Young <nyoung@uptime.ventures>"]
description = "Universal frontmatter parser."
repository = "https://gitlab.com/secretfader/matter"
keywords = ["frontmatter", "yaml", "json", "toml"]
readme = "../README.md"
license = "BSD-3-Clause"
edition = "2018"

[dependencies]
failure = "0.1.4"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.8", optional = true }
toml = { version = "0.4", optional = true }
regex = "1.1.0"
lazy_static = "1.2.0"
structopt = "0.2"

[features]
default = []
json = ["serde", "serde_json"]
yaml = ["serde", "serde_yaml"]

[[bin]]
path = "src/main.rs"
name = "matter"
